### PR TITLE
add Display > Show Water Level

### PR DESCRIPTION
**Pull request by o7Moon**
20240527_18h14m17s_grim

### CODE REVIEW

**Comment by o7Moon** [comment]
hmm i expected existing code would already be formatted the way `clang-format` does it but parts of it seem to have changed

**Comment by Redcrafter** [comment]
i kept some things unformatted yeah. should have seen this coming

**Comment by o7Moon** [comment]
i can go back through this and `// clang-format off` the sections that matter?

**Comment by Redcrafter** [comment]
it only really matters for that one array. the rest is kinda whatever

**Pull request merged**
